fix: resolve unexpected error caused by pathlib (#29)
Error: unexpected error: 'PosixPath' object does not support the context
manager protocol

Fixed by removing `with` statement before Path() functions.